export const media = {
  hero: '/media/hero.jpg',
  ask: '/media/ask.jpg',
  language: '/media/language.jpg',
  verified: '/media/verified.jpg',
  app: '/media/app.jpg',
  rent: '/media/rent.jpg',
  sell: '/media/sell.jpg',
  apply: '/media/apply.jpg',
  control: '/media/control.jpg',
  ios: '/media/ios.jpg',
  android: '/media/android.jpg',
  sambinha: '/media/sambinha.jpg',
  boston: '/media/boston.jpg',
  jersey: '/media/jersey.jpg',
  kitchen: '/media/kitchen.jpg',
  street: '/media/street.jpg',
  chat: '/media/chat.jpg',
  splash: '/media/splash.jpg',
  story: '/media/story.jpg',
  howAsk: '/media/how-ask.jpg',
  howApp: '/media/how-app.jpg',
  howDone: '/media/how-done.jpg',
  howMeet: '/media/how-meet.jpg',
  howRenovation: '/media/how-renovation.jpg',
  fitness: '/media/fitness.jpg',
  chef: '/media/chef.jpg',
  beauty: '/media/beauty.jpg',
  serviceHousing: '/media/service-housing.jpg',
  serviceCleaning: '/media/service-cleaning.jpg',
  serviceHair: '/media/service-hair.jpg',
  serviceFitness: '/media/service-fitness.jpg',
  serviceChef: '/media/service-chef.jpg',
  serviceLegal: '/media/service-legal.jpg',
  serviceHome: '/media/service-home.jpg',
  serviceGardening: '/media/service-gardening.jpg',
  matchLanguage: '/media/match-language.jpg',
  matchVerified: '/media/match-verified.jpg',
  matchApp: '/media/match-app.jpg',
  serviceRoom: '/media/service-room.jpg',
  housingSell: '/media/housing-sell.jpg',
  housingApply: '/media/housing-apply.jpg',
  controlPro: '/media/control-pro.jpg',
  langWords: '/media/lang-words.jpg',
  langMatch: '/media/lang-match.jpg',
  langChat: '/media/lang-chat.jpg',
  scaleMarkets: '/media/scale-markets.jpg',
  scaleChat: '/media/scale-chat.jpg',
  scaleHousing: '/media/scale-housing.jpg',
  aboutHero: '/media/about-hero.jpg',
} as const

export function portrait(id: string) {
  const n = Number(id.replace(/\D/g, '')) || 1
  return `/media/p${((n - 1) % 12) + 1}.jpg`
}
